/* Split an app's content into what ships and what does not.
 *
 * Today every question — stem, correct answer and rationale — is inlined in
 * index.html, so a free visitor already holds the entire bank. This moves the
 * paid questions out of the bundle:
 *
 *   apps/<slug>/src/content-free.js   the glossary plus a small sample set.
 *                                     A classic script assigning window.DATA,
 *                                     so it loads synchronously and the app's
 *                                     boot order is unchanged.
 *   content/<slug>/bank.json          every question with its answer key.
 *                                     Never committed, never served as a file —
 *                                     uploaded to a private bucket and handed
 *                                     out by the content function.
 *
 * Usage: node scripts/split-content.mjs [slug ...]     (default: every app)
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { readdirSync } from "node:fs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const FREE_QUESTIONS = 10;          // matches the free tier's one practice set

const slugs = process.argv.slice(2).length
  ? process.argv.slice(2)
  : readdirSync(join(ROOT, "apps")).filter(s =>
      s !== "hub" && existsSync(join(ROOT, "apps", s, "src", "index.html")));

/* A sample that spans categories reads as a fair taste of the bank rather than
   the first ten of one topic. Deterministic so rebuilds do not churn. */
function pickFree(questions, n) {
  const byCat = new Map();
  for (const q of questions) {
    if (!byCat.has(q.cat)) byCat.set(q.cat, []);
    byCat.get(q.cat).push(q);
  }
  const cats = [...byCat.keys()].sort();
  const out = [];
  let i = 0;
  while (out.length < Math.min(n, questions.length)) {
    let added = false;
    for (const c of cats) {
      const list = byCat.get(c);
      if (i < list.length) { out.push(list[i]); added = true; }
      if (out.length >= n) break;
    }
    if (!added) break;
    i++;
  }
  return out;
}

let failed = false;

for (const slug of slugs) {
  const htmlPath = join(ROOT, "apps", slug, "src", "index.html");
  if (!existsSync(htmlPath)) { console.error(`  skip ${slug}: no index.html`); continue; }

  const html = await readFile(htmlPath, "utf8");

  if (html.includes("./content-free.js")) {
    console.log(`  ${slug}: already split`);
    continue;
  }

  const m = html.match(/^const DATA = (\{.*\});?\s*$/m);
  if (!m) { console.error(`  FAIL ${slug}: could not find the DATA declaration`); failed = true; continue; }

  let data;
  try { data = JSON.parse(m[1]); }
  catch (err) { console.error(`  FAIL ${slug}: DATA is not valid JSON — ${err.message}`); failed = true; continue; }

  const cards = data.cards || [];
  const questions = data.questions || [];
  const free = pickFree(questions, FREE_QUESTIONS);
  const freeIds = new Set(free.map(q => q.id));

  // The glossary is free on every plan, so it stays in the bundle and keeps
  // working offline. Only the question bank is held back.
  const bundle = {
    cards,
    questions: free,
    meta: { total: questions.length, free: free.length, split: true }
  };

  await writeFile(
    join(ROOT, "apps", slug, "src", "content-free.js"),
    "/* Generated by scripts/split-content.mjs — do not edit by hand.\n" +
    "   The glossary and a sample of the question bank. The rest is served\n" +
    "   from the content function once entitlement is confirmed. */\n" +
    "window.DATA = " + JSON.stringify(bundle) + ";\n"
  );

  // The server keeps everything: it needs the free items too, because grading
  // asks it for answers by id and should not care which tier an item came from.
  await mkdir(join(ROOT, "content", slug), { recursive: true });
  await writeFile(
    join(ROOT, "content", slug, "bank.json"),
    JSON.stringify({ slug, total: questions.length, freeIds: [...freeIds], questions }) + "\n"
  );

  // Replace the inline declaration with the tag that loads the free bundle.
  const patched = html.replace(
    m[0],
    "/* Content is split: window.DATA is assigned by content-free.js, loaded\n" +
    "   above. The paid questions arrive through js/content.js. */"
  ).replace(
    '<script src="./entitlements.js"></script>',
    '<script src="./content-free.js"></script>'
  );

  const withLoader = patched.includes("./content-free.js")
    ? patched
    : patched.replace(
        '<link rel="manifest" href="./manifest.webmanifest">',
        '<link rel="manifest" href="./manifest.webmanifest">\n<script src="./content-free.js"></script>'
      );

  await writeFile(htmlPath, withLoader);

  const before = Buffer.byteLength(html);
  const after = Buffer.byteLength(withLoader);
  console.log(
    `  ${slug}: ${questions.length} questions → ${free.length} bundled, ` +
    `${questions.length - free.length} held back  (index.html ${(before/1024).toFixed(0)}KB → ${(after/1024).toFixed(0)}KB)`
  );
}

process.exit(failed ? 1 : 0);
