/* Push a bank correction out to the free sample.
 *
 * content-free.js holds a copy of ten questions that also live in
 * content/<slug>/bank.json. split-content.mjs created both in one pass and
 * then refuses to run again ("already split"), so once a bank is corrected
 * there is otherwise no way to get the fix into the free bundle — the paid
 * app serves the corrected item while the free sample keeps the old one.
 *
 * This re-derives only the `questions` array, from the bank, for the ids the
 * bank already marks free. The glossary and everything else are untouched.
 *
 * Usage: node scripts/sync-free.mjs [slug ...]     (default: every bank)
 *        node scripts/sync-free.mjs --check        report drift, change nothing
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CONTENT = join(ROOT, "content");
const args = process.argv.slice(2);
const checkOnly = args.includes("--check");
const wanted = args.filter(a => !a.startsWith("--"));

if (!existsSync(CONTENT)) {
  console.error("  no content/ directory — unpack the paid content first (see LAUNCH.md §2)");
  process.exit(1);
}

const slugs = wanted.length ? wanted
  : readdirSync(CONTENT).filter(s => existsSync(join(CONTENT, s, "bank.json")));

let drifted = 0;

for (const slug of slugs) {
  const freePath = join(ROOT, "apps", slug, "src", "content-free.js");
  if (!existsSync(freePath)) { console.log(`  skip ${slug}: no content-free.js`); continue; }

  const bank = JSON.parse(readFileSync(join(CONTENT, slug, "bank.json"), "utf8"));
  const src = readFileSync(freePath, "utf8");
  const m = src.match(/window\.DATA = (\{[\s\S]*\});?\s*$/);
  if (!m) { console.error(`  FAIL ${slug}: could not find the window.DATA assignment`); process.exitCode = 1; continue; }

  const data = JSON.parse(m[1]);
  const byId = new Map((bank.questions || []).map(q => [q.id, q]));

  // Keep the order the bundle already ships — this replaces content, not the
  // selection, so a rebuild never reshuffles what a free visitor sees.
  const rebuilt = (data.questions || []).map(q => byId.get(q.id) ?? q);
  const missing = (data.questions || []).filter(q => !byId.has(q.id)).map(q => q.id);
  if (missing.length) console.log(`  note ${slug}: not in the bank, left as-is — ${missing.join(", ")}`);

  if (JSON.stringify(rebuilt) === JSON.stringify(data.questions)) {
    console.log(`  ok   ${slug}: free sample matches the bank`);
    continue;
  }

  drifted++;
  const changed = rebuilt.filter((q, i) => JSON.stringify(q) !== JSON.stringify(data.questions[i])).map(q => q.id);
  console.log(`  ${checkOnly ? "DRIFT" : "sync"} ${slug}: ${changed.length} question(s) differ — ${changed.join(", ")}`);
  if (checkOnly) continue;

  data.questions = rebuilt;
  writeFileSync(freePath,
    "/* Generated by scripts/split-content.mjs — do not edit by hand.\n" +
    "   The glossary and a sample of the question bank. The rest is served\n" +
    "   from the content function once entitlement is confirmed. */\n" +
    "window.DATA = " + JSON.stringify(data) + ";\n");
}

console.log(`\n  ${drifted} app(s) ${checkOnly ? "out of sync" : "updated"}`);
if (checkOnly && drifted) process.exit(1);
